CREATE TABLE venda(

xNome VARCHAR(150),
CNPJ VARCHAR(50),
xLgr VARCHAR(30),
nro VARCHAR(15),
xBairro VARCHAR(60),
xMun VARCHAR(60),
UF VARCHAR(80),
ID INT PRIMARY KEY AUTO_INCREMENT
);

SELECT * FROM venda;

DROP TABLE venda;